top_srcdir   = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
top_builddir = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
srcdir       = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/os
builddir     = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/os
VPATH        = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
