top_srcdir   = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
top_builddir = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
srcdir       = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules
builddir     = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules
VPATH        = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

