top_srcdir   = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
top_builddir = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
srcdir       = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/loggers
builddir     = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/loggers
VPATH        = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/loggers

include $(top_srcdir)/build/special.mk

