top_srcdir   = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
top_builddir = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
srcdir       = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/mappers
builddir     = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/mappers
VPATH        = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/mappers

include $(top_srcdir)/build/special.mk

