top_srcdir   = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
top_builddir = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
srcdir       = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/dav/lock
builddir     = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/dav/lock
VPATH        = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/dav/lock
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
