top_srcdir   = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
top_builddir = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
srcdir       = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/cache
builddir     = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/cache
VPATH        = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/cache

include $(top_srcdir)/build/special.mk

