top_srcdir   = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
top_builddir = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
srcdir       = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/os/unix
builddir     = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/os/unix
VPATH        = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
