top_srcdir   = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
top_builddir = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
srcdir       = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/server/mpm
builddir     = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/server/mpm
VPATH        = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
