top_srcdir   = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
top_builddir = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
srcdir       = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/http
builddir     = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/http
VPATH        = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/http

include $(top_srcdir)/build/special.mk

