######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 26 19:10:20 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt_test1.cpp
