top_srcdir   = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
top_builddir = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
srcdir       = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/echo
builddir     = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/echo
VPATH        = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/modules/echo

include $(top_srcdir)/build/special.mk

