top_srcdir   = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
top_builddir = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4
srcdir       = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/server/mpm/prefork
builddir     = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/server/mpm/prefork
VPATH        = /home/akaedu/project/xinge-project/httpd/httpd-2.2.4/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
